
export default {
    arrest_data: [
       {
    caseID: 'hKm567',
    details: "Fraud",
    priority: 'medium',
    officersOnScene: ["Officer Musoke", "Officer Katongole"],
    dateCreated: "02/18/2024",
    postedBy: "S. Mugisha",
    evidence: "Forgery documents",
    status: "closed",
    perp_name: "Namugera Letit",
    agency: "ISO",
    location: 'Entebbe, Uganda',
    desc: 'Several individuals reported unauthorized transactions from their bank accounts. Total losses exceed UGX 50,000,000. Investigations ongoing to trace the source of the fraud and apprehend the perpetrators.',
    suspects: ["Kato", "Namugera"]
  },
  {
    caseID: 'wEr123',
    details: "Burglary",
    priority: 'medium',
    officersOnScene: ["Officer Ssempijja", "Officer Nankunda"],
    dateCreated: "02/21/2024",
    postedBy: "J. Opolot",
    perp_name: "Musoke Mike",
    evidence: "Fingerprints",
    agency: "ISO",
    location: 'Jinja, Uganda',
    desc: 'Multiple residences were broken into overnight. Valuables including electronics and jewelry were stolen. Investigation ongoing to identify and apprehend the perpetrators.',
    suspects: ["Lubega", "Ssebunya"]
  },
  {
    caseID: 'aBc456',
    details: "Assault",
    priority: 'low',
    officersOnScene: ["Officer Lubwama"],
    dateCreated: "02/19/2024",
    perp_name: "Swabrah Madina",
    postedBy: "M. Namutebi",
    evidence: "Surveillance footage",
    agency: "ESO",
    location: 'Mbarara, Uganda',
    desc: 'A physical altercation occurred at a local bar resulting in injuries to one individual. The assailant fled the scene. Police are investigating the incident.',
    suspects: ["Ssempijja"]
  },
  {
    caseID: 'pQt789',
    details: "Robbery",
    priority: 'high',
    perp_name: "Emma katungi",
    officersOnScene: ["Officer Mwesigwa", "Officer Namubiru", "Officer Ssebunya"],
    dateCreated: "02/17/2024",
    postedBy: "A. Nalubega",
    evidence: "Weapon recovered",
    status: "open",
    agency: "CMI",
    location: 'Masaka, Uganda',
    desc: 'An armed robbery occurred at a local bank. Several hostages were taken, and a significant amount of money was stolen. Police have surrounded the building and negotiations are ongoing.',
    suspects: ["Mugabi", "Ssemakula"]
  },
  {
    caseID: 'lMn234',
    details: "Missing Person",
    priority: 'medium',
    perp_name: "Allura Denton",
    officersOnScene: ["Officer Opolot", "Officer Kamya"],
    dateCreated: "02/16/2024",
    postedBy: "L. Mbabazi",
    evidence: "Missing posters",
    status: "open",
    agency: "CMI",
    location: 'Fort Portal, Uganda',
    desc: 'A young woman was reported missing by her family. She was last seen leaving her workplace. Investigations are underway to locate her whereabouts.',
    suspects: ["Kasaija", "Nabadda"]
  },
  {
    caseID: 'qRs345',
    details: "Drug Trafficking",
    priority: 'high',
    officersOnScene: ["Officer Namukwaya", "Officer Katusiime", "Officer Kiggundu"],
    dateCreated: "02/15/2024",
    postedBy: "P. Kyomuhendo",
    evidence: "Seized drugs",
    perp_name: "Nakalembe Martha",
    status: "open",
    agency: "Police",
    location: 'Gulu, Uganda',
    desc: 'A large shipment of narcotics was intercepted at the border. Investigations ongoing to identify the traffickers and dismantle the network.',
    suspects: ["Kibirige", "Namara", "Mugisha"]
  },
  {
    caseID: 'tUv678',
    details: "Human Trafficking",
    priority: 'high',
    officersOnScene: ["Officer Kamugisha", "Officer Nalukenge", "Officer Kizza"],
    dateCreated: "02/14/2024",
    postedBy: "R. Tumusiime",
    perp_name: "Apio Maureen",
    evidence: "Rescued victims",
    status: "closed",
    agency: "CMI",
    location: 'Mbale, Uganda',
    desc: 'Several individuals were rescued from a trafficking ring operating in the region. Investigations ongoing to apprehend the perpetrators and provide support to the victims.',
    suspects: ["Mukasa", "Nalubega", "Ssebunya"]
  },
  {
    caseID: 'gHw567',
    details: "Counterfeiting",
    priority: 'medium',
    officersOnScene: ["Officer Kasirye", "Officer Namuganza"],
    dateCreated: "02/13/2019",
    postedBy: "B. Ssebunya",
    evidence: "Counterfeit currency",
    perp_name: "Apio Maureen",
    status: "closed",
    agency: "CT",
    location: 'Kasese, Uganda',
    desc: 'Fake currency notes were detected circulating in local markets. Investigations are underway to identify the source of the counterfeit currency.',
    suspects: ["Nabukeera", "Kizza"]
  },
  {
    caseID: 'rXy890',
    details: "Cybercrime",
    priority: 'high',
    officersOnScene: ["Officer Akello", "Officer Ssenyondo"],
    dateCreated: "02/12/2020",
    postedBy: "D. Kato",
    evidence: "Hacked accounts",
    status: "closed",
    perp_name: "Apio Maureen",
    agency: "CT",
    location: 'Lira, Uganda',
    desc: 'Several individuals reported unauthorized access to their online accounts. Investigations ongoing to trace the hackers and secure the compromised systems.',
    suspects: ["Owino", "Namuwenge"]
  },
    ]
    }