
export default {
  allInvestigations: [
    {
      id: 'uGx789',
      intelType: "Kidnapping",
      priority: 'high',
      officersOnScene: ["Officer Nalubega", "Officer Okech", "Officer Wasike"],
      dateCreated: "02/20/2024",
      postedBy: "K. Odongo",
      victims: ["Nakato Jalia", "Ojok Ronald", "Namugenyi Patricia"],
      status: "closed",
      agency:"Police",
      location: 'Kampala, Uganda',
      desc: 'Three individuals were reported missing in separate incidents over the past week. Families received ransom demands. Investigations underway to locate and rescue the victims.',
      suspects: ["Ogwang", "Akena", "Nabukenya"]
    },
    {
      id: 'hKm567',
      intelType: "Fraud",
      priority: 'medium',
      officersOnScene: ["Officer Musoke", "Officer Katongole"],
      dateCreated: "02/18/2024",
      postedBy: "S. Mugisha",
      victims: ["Kasaija Amos", "Nabulya Sarah"],
      status: "closed",
      agency:"Police",
      location: 'Entebbe, Uganda',
      desc: 'Several individuals reported unauthorized transactions from their bank accounts. Total losses exceed UGX 50,000,000. Investigations ongoing to trace the source of the fraud and apprehend the perpetrators.',
      suspects: ["Kato", "Namugera"]
    },
    {
      id: 'wEr123',
      intelType: "Burglary",
      priority: 'medium',
      officersOnScene: ["Officer Ssempijja", "Officer Nankunda"],
      dateCreated: "02/21/2024",
      postedBy: "J. Opolot",
      agency:"Police",
      victims: ["Mukasa Geoffrey", "Nalubega Mercy"],
      status: "open",
      location: 'Jinja, Uganda',
      desc: 'Multiple residences were broken into overnight. Valuables including electronics and jewelry were stolen. Investigation ongoing to identify and apprehend the perpetrators.',
      suspects: ["Lubega", "Ssebunya"]
    },
    {
      id: 'aBc456',
      intelType: "Assault",
      priority: 'low',
      agency:"Police",
      officersOnScene: ["Officer Lubwama"],
      dateCreated: "02/19/2024",
      postedBy: "M. Namutebi",
      victims: ["Kato Joseph"],
      status: "closed",
      location: 'Mbarara, Uganda',
      desc: 'A physical altercation occurred at a local bar resulting in injuries to one individual. The assailant fled the scene. Police are investigating the incident.',
      suspects: ["Ssempijja Leonard"]
    },
    {
      agency:"Police",
      id: 'pQt789',
      intelType: "Robbery",
      priority: 'high',
      officersOnScene: ["Officer Mwesigwa", "Officer Namubiru", "Officer Ssebunya"],
      dateCreated: "02/17/2024",
      postedBy: "A. Nalubega",
      victims: ["Kakooza David", "Nakazzi Esther"],
      status: "open",
      location: 'Masaka, Uganda',
      desc: 'An armed robbery occurred at a local bank. Several hostages were taken, and a significant amount of money was stolen. Police have surrounded the building and negotiations are ongoing.',
      suspects: ["Mugabi", "Ssemakula"]
    },
    {
      id: 'lMn234',
      intelType: "Missing Person",
      priority: 'medium',
      agency:"Police",
      officersOnScene: ["Officer Opolot", "Officer Kamya"],
      dateCreated: "02/16/2024",
      postedBy: "L. Mbabazi",
      victims: ["Mukisa Gloria"],
      status: "open",
      location: 'Fort Portal, Uganda',
      desc: 'A young woman was reported missing by her family. She was last seen leaving her workplace. Investigations are underway to locate her whereabouts.',
      suspects: ["Kasaija", "Nabadda"]
    },
    {
      id: 'qRs345',
      intelType: "Drug Trafficking",
      priority: 'high',
      officersOnScene: ["Officer Namukwaya", "Officer Katusiime", "Officer Kiggundu"],
      dateCreated: "02/15/2024",
      postedBy: "P. Kyomuhendo",
      victims: [],
      agency:"Police",
      status: "open",
      location: 'Gulu, Uganda',
      desc: 'A large shipment of narcotics was intercepted at the border. Investigations ongoing to identify the traffickers and dismantle the network.',
      suspects: ["Kibirige", "Namara", "Mugisha"]
    },
    {
      id: 'tUv678',
      intelType: "Human Trafficking",
      priority: 'high',
      agency:"Police",
      officersOnScene: ["Officer Kamugisha", "Officer Nalukenge", "Officer Kizza"],
      dateCreated: "02/14/2024",
      postedBy: "R. Tumusiime",
      victims: ["Nakalema Judith", "Ssempijja Ivan", "Kasumba Faith"],
      status: "closed",
      location: 'Mbale, Uganda',
      desc: 'Several individuals were rescued from a trafficking ring operating in the region. Investigations ongoing to apprehend the perpetrators and provide support to the victims.',
      suspects: ["Mukasa", "Nalubega", "Ssebunya"]
    },
    {
      id: 'gHw567',
      intelType: "Counterfeiting",
      priority: 'medium',
      officersOnScene: ["Officer Kasirye", "Officer Namuganza"],
      dateCreated: "02/13/2024",
      postedBy: "B. Ssebunya",
      agency:"Police",
      victims: [],
      status: "closed",
      location: 'Kasese, Uganda',
      desc: 'Fake currency notes were detected circulating in local markets. Investigations are underway to identify the source of the counterfeit currency.',
      suspects: ["Nabukeera", "Kizza"]
    },
    {
      id: 'rXy890',
      intelType: "Cybercrime",
      priority: 'high',
      agency:"Police",
      officersOnScene: ["Officer Akello", "Officer Ssenyondo"],
      dateCreated: "02/12/2024",
      postedBy: "D. Kato",
      victims: ["Nakato Irene", "Mukasa Charles"],
      status: "closed",
      location: 'Lira, Uganda',
      desc: 'Several individuals reported unauthorized access to their online accounts. Investigations ongoing to trace the hackers and secure the compromised systems.',
      suspects: ["Owino", "Namuwenge"]
    },
]
}